name: AnalyzeExplodingTopics		

on:		
  schedule:		
    - cron:  '30 * * * *'		
jobs:		
  build:		
    runs-on: ubuntu-latest		
    steps:		
     - name: Analyze Exploding Topics		
       run: curl -s -X POST $ASK_HOST/api/analyzeExplodingTopics
       env:
        ASK_HOST: ${{ secrets.ASK_HOST }}
        ASK_TOKEN: ${{ secrets.ASK_TOKEN }}
