name: AnalyzeGoogleTrends		

on:		
  schedule:		
    - cron:  '1 * * * *'		
jobs:		
  build:		
    runs-on: ubuntu-latest		
    steps:		
     - name: Analyze Google Trends		
       run: curl -s -X POST $ASK_HOST/api/analyzeTodaysGoogleTrends
       env:
        ASK_HOST: ${{ secrets.ASK_HOST }}
        ASK_TOKEN: ${{ secrets.ASK_TOKEN }}
