name: AnalyzeSearchResults	

on:		
  schedule:		
    - cron:  '*/5 * * * *'
      
jobs:		
  build:		
    runs-on: ubuntu-latest		
    steps:		
     - name: Analyze Search		
       run: curl -s -X POST $ASK_HOST/api/analyzeSearchResults
       env:
        ASK_HOST: ${{ secrets.ASK_HOST }}
        ASK_TOKEN: ${{ secrets.ASK_TOKEN }}
