name: AnalyzeTrendingSearches		

on:		
  schedule:		
    - cron:  '0 */3 * * *'
jobs:		
  build:		
    runs-on: ubuntu-latest		
    steps:		
     - name: Analyze Trending Searches		
       run: echo "paused" #curl -s -X POST $ASK_HOST/api/analyzeTrendingSearches
       env:
        ASK_HOST: ${{ secrets.ASK_HOST }}
        ASK_TOKEN: ${{ secrets.ASK_TOKEN }}
