name: UpdateAuth2

on:		
  schedule:		
    - cron:  '*/16 * * * *'		
jobs:		
  build:		
    runs-on: ubuntu-latest		
    steps:		
     - name: Update Auth2		
       run: echo "Skip" #curl -s -X POST $ASK_HOST/api/updateAuth2
       env:
        ASK_HOST: ${{ secrets.ASK_HOST }}
        ASK_TOKEN: ${{ secrets.ASK_TOKEN }}
