name: UpdateRandomResults

on:		
  schedule:		
    - cron:  '22 * * * *'		
jobs:		
  build:		
    runs-on: ubuntu-latest		
    steps:		
     - name: Update Random Results		
       run: curl -s -X POST $ASK_HOST/api/updateRandomResults
       env:
        ASK_HOST: ${{ secrets.ASK_HOST }}
        ASK_TOKEN: ${{ secrets.ASK_TOKEN }}
